// Valmistusohjeet — lyhyet vaiheet per resepti.
// Yhdistetään DEFAULT_RECIPES-kohteisiin recipes.jsx:ssä.
const RECIPE_STEPS = {
  r01: ['Sekoita jauheliha, hienonnettu sipuli, muna, korppujauhot ja maitoon liotettu leipä.','Mausta suolalla ja pippurilla. Anna massan turvota 10 min.','Pyörittele tasakokoiset pullat ja paista pannulla voissa kauniin ruskeiksi.','Keitä perunat kypsiksi, soseuta ja lisää lämmin maito ja voi.','Tarjoile lihapullat muusin, ruskean kastikkeen ja puolukan kanssa.'],
  r02: ['Kuori ja kuutioi perunat, porkkanat ja purjo. Keitä ne kalaliemessä noin 15 min.','Lisää lohikuutiot ja kerma. Anna kiehua 5–7 min, ettei lohi hajoa.','Mausta suolalla ja valkopippurilla, ripottele tilliä päälle.'],
  r03: ['Keitä makaroni runsaassa suolatussa vedessä lähes kypsäksi.','Ruskista jauheliha sipulin kanssa, mausta suolalla, pippurilla ja paprikalla.','Sekoita pastaan, kaada vuokaan ja kaada päälle maito-munaseos.','Paista 200 °C noin 35 min kunnes pinta on kullanruskea.'],
  r04: ['Kuutioi sianliha ja naudanliha. Lado vuokaan kerroksittain sipulin ja porkkanan kanssa.','Mausta suolalla, maustepippurilla ja laakerinlehdellä.','Kaada päälle vettä niin että lihat juuri peittyvät.','Hauduta uunissa 150 °C 2,5–3 tuntia kannen alla. Tarjoile perunamuusin kanssa.'],
  r05: ['Pilko kanafileet kuutioiksi ja kuullota kattilassa.','Lisää pilkotut juurekset ja kanaliemi. Keitä 15 min.','Lisää purjo ja keitä vielä 5 min. Mausta yrteillä, suolalla ja pippurilla.'],
  r06: ['Liota herneet edellisenä iltana runsaassa kylmässä vedessä.','Keitä herneet ja kuutioitu sianliha kannen alla 1,5–2 tuntia.','Lisää sipuli ja mausteet kypsennyksen loppupuolella.','Tarjoile sinapin ja ruisleivän kanssa.'],
  r07: ['Esikypsennä kaalinlehdet kiehuvassa vedessä pehmeiksi.','Sekoita jauheliha, esikeitetty riisi, sipuli ja mausteet täytteeksi.','Kääri täytteet kaalinlehtien sisään ja lado vuokaan.','Voitele siirapilla ja paista 175 °C noin 1 h. Tarjoile puolukan kanssa.'],
  r08: ['Asettele lohifilee uunipellille, valele oliiviöljyllä ja sitruunamehulla.','Mausta suolalla ja pippurilla, ripottele tuoretta tilliä.','Paista 200 °C 15–20 min kunnes liha hilseilee haarukalla.','Tarjoile uuniperunoiden ja vihersalaatin kera.'],
  r09: ['Sulata pinaatti ja purista neste pois.','Sekoita kaikki ainekset taikinaksi ja anna turvota 10 min.','Paista pieniä lettuja pannulla voissa molemmin puolin.','Tarjoile puolukkahillon kanssa.'],
  r10: ['Kuori ja suikaloi perunat ohuiksi. Hienonna sipulit ja kuullota voissa.','Lado vuokaan kerroksittain perunat, sipuli ja anjovis.','Kaada päälle anjovisliemi ja kerma.','Paista 200 °C noin 50 min kunnes pinta on kauniin ruskea.'],
  r11: ['Kuutioi naudanliha ja ruskista kattilan pohjalla.','Lisää vesi, laakerinlehti ja maustepippurit. Hauduta tunti.','Lisää kuutioidut juurekset ja keitä 20 min lisää.','Tarkista mauste, tarjoile ruisleivän kanssa.'],
  r12: ['Keitä pasta suolatussa vedessä al dente.','Pilko broileri ja paista pannulla. Lisää kerma ja pesto.','Sekoita pasta kastikkeeseen ja anna kiehahtaa.','Ripottele päälle parmesaania ennen tarjoilua.'],
  r13: ['Kuullota hienonnettu sipuli pannulla.','Lisää jauheliha ja ruskista. Mausta suolalla ja pippurilla.','Lisää tomaattimurska ja anna hautua 10 min.','Tarjoile keitetyn riisin kanssa.'],
  r14: ['Kuullota hienonnettu sipuli ja valkosipuli oliiviöljyssä.','Lisää jauheliha ja ruskista hyvin. Lisää tomaattimurska ja yrtit.','Anna hautua matalalla lämmöllä 20 min.','Keitä spagetti ja tarjoile kastikkeen ja parmesaanin kanssa.'],
  r15: ['Suikaloi kana ja marinoi soijakastikkeessa 10 min.','Paista kuumalla pannulla, lisää inkivääri ja valkosipuli.','Lisää wokkivihannekset ja kuumenna rapsakoiksi.','Tarjoile keitetyn riisin kera.'],
  r16: ['Tee jauhelihakastike kuten bolognese (n. 20 min).','Tee valkokastike voista, jauhoista ja maidosta.','Lado vuokaan kerroksittain levyt, lihakastike, valkokastike ja juusto.','Paista 200 °C noin 30 min kunnes pinta kuplii ja kullistuu.'],
  r17: ['Kuutioi perunat, sipulit ja makkara.','Paista kaikki pannulla yhdessä kunnes saavat väriä.','Mausta suolalla ja pippurilla, tarjoile paistetun munan ja suolakurkun kanssa.'],
  r18: ['Kuutioi kala, perunat ja juurekset.','Keitä juurekset kalaliemessä 15 min.','Lisää kala ja keitä 5 min. Mausta tillillä ja maustepippurilla.'],
  r19: ['Sekoita ainekset tasaiseksi taikinaksi ja anna turvota 15 min.','Kaada voideltuun pellille ja paista 225 °C noin 25 min.','Anna jäähtyä ja tarjoile mansikkahillon ja kermavaahdon kanssa.'],
  r20: ['Pese ja pistele perunat. Paista 200 °C 50–60 min.','Halkaise perunat ja levitä smetana sekä täyte.','Ripottele juustoraaste ja gratinoi vielä 5 min.','Viimeistele ruohosipulilla.'],
  r21: ['Tee ohut ruistaikina ja kauli soikeiksi pohjiksi.','Levitä riisipuuro pohjille ja rypytä reunat.','Paista 250 °C noin 15 min ja voitele voilla.','Tarjoile munavoin kanssa.'],
  r22: ['Suikaloi naudanliha ja paista nopeasti pannulla.','Lisää sipuli ja suolakurkku, kuullota.','Lisää kerma ja sinappi, anna kiehahtaa.','Tarjoile riisin kanssa.'],
  r23: ['Marinoi ja paista kanafileet, anna vetäytyä ja viipaloi.','Asettele salaatti, tomaatti, kurkku ja feta lautaselle.','Lisää kana päälle ja valele vinaigrettella.'],
  r24: ['Keitä pasta al denteksi.','Pilko lohi ja kuullota pannulla. Lisää kerma ja sitruunamehu.','Sekoita pasta kastikkeeseen, viimeistele tillillä.'],
  r25: ['Kuullota sipuli ja valkosipuli kattilassa.','Lisää tomaatit ja kasvisliemi, keitä 15 min.','Soseuta sauvasekoittimella ja lisää kerma.','Mausta basilikalla ja tarjoile leivän kanssa.'],
  r26: ['Soseuta kikherneet, sipuli, kaurahiutaleet ja muna karkeaksi massaksi.','Pyörittele pyörykät ja paista pannulla.','Tarjoile perunamuusin ja sinappikastikkeen kanssa.'],
  r27: ['Kauli pohja, levitä tomaattikastike ja juusto.','Lisää täytteet ja oregano.','Paista 250 °C noin 10–12 min.'],
  r28: ['Keitä pasta suolatussa vedessä.','Sekoita tomaattikastike, tonnikala, oliivit ja kaprikset.','Yhdistä pastaan ja tarjoile.'],
  r29: ['Suikaloi perunat ja sipulit ohuiksi.','Lado vuokaan perunat, kinkku ja sipulit kerroksittain.','Kaada päälle kerma ja paista 200 °C 50 min.'],
  r30: ['Soseuta kikherneet, sipuli, valkosipuli ja mausteet.','Pyörittele pieniä palloja ja paista runsaassa öljyssä.','Tarjoile pita-leivän, salaatin ja tahini-kastikkeen kanssa.'],
  r31: ['Kuullota sipuli ja currytahna pannulla.','Lisää kanasuikaleet ja paista. Kaada päälle kookosmaito.','Anna hautua 10 min, tarjoile riisin kanssa.'],
  r32: ['Jauha maksa lihamyllyssä tai sauvalla.','Sekoita keitettyyn riisiin, lisää sipuli, rusinat, sirappi ja mausteet.','Kaada vuokaan ja paista 175 °C noin 50 min.'],
  r33: ['Sekoita jauheliha, hienonnettu punajuuri, kaprikset ja sipuli.','Muotoile pihveiksi ja paista pannulla voissa.','Tarjoile perunamuusin kanssa.'],
  r34: ['Avaa silakat, mausta suolalla.','Pyörittele korppujauhoissa ja paista pannulla voissa.','Tarjoile perunoiden ja sitruunan kanssa.'],
  r35: ['Kuullota sipuli ja inkivääri kattilassa.','Lisää porkkanat ja kasvisliemi, keitä 15 min.','Soseuta tasaiseksi, lisää kerma ja siemenet.'],
  r36: ['Kuullota sipuli ja porkkana kattilassa.','Lisää linssit, tomaattimurska ja kookosmaito.','Mausta currylla, keitä 20 min.'],
  r37: ['Pilko sienet ja paista pannulla. Lisää sipuli.','Kaada päälle kerma ja anna kiehua 5 min.','Mausta timjamilla, tarjoile perunoiden kanssa.'],
  r38: ['Sulata käristys pannulla voissa.','Lisää sipuli, katajanmarjat ja riistaliemi.','Hauduta 20 min, tarjoile perunamuusin ja puolukan kera.'],
  r39: ['Sulata käristys pannulla voissa.','Lisää sipuli ja vesi, hauduta 20 min.','Tarjoile perunamuusin, puolukan ja suolakurkun kanssa.'],
  r40: ['Keitä perunat ja soseuta. Sekoita maitoon ja munaan.','Ruskista jauheliha sipulin kanssa.','Lado vuokaan jauheliha ja perunasose. Paista 200 °C 30 min.'],
  r41: ['Kuori ja kuutioi bataatit. Kuullota sipuli ja inkivääri.','Lisää bataatti ja kasvisliemi, keitä 15 min.','Soseuta, lisää kookosmaito ja chili.'],
  r42: ['Suikaloi vihannekset ja tofu.','Paista wokissa kovalla lämmöllä, lisää soijakastike.','Tarjoile riisinuudeleiden kanssa.'],
  r43: ['Levitä taikina pannuun. Lisää kastike ja täytteet.','Paista 250 °C 10–12 min.','Anna hetki vetäytyä, paloittele ja tarjoile.'],
  r44: ['Ruskista jauheliha ja mausta tex-mex-mausteilla.','Lämmitä tortillat. Asettele täytteet pöytään.','Anna jokaisen koota oma tortillansa.'],
  r45: ['Paista kalapuikot ohjeen mukaan uunissa.','Tee perunamuusi ja kuumenna herneet.','Tarjoile sitruunan ja remoulade-kastikkeen kanssa.'],
  r46: ['Riko munat kulhoon ja vatkaa.','Kaada pannulle ja anna hyytyä matalalla lämmöllä.','Lisää juustoraaste ja taita kahtia. Tarjoile salaatin kanssa.'],
  r47: ['Kuutioi tofu ja paista pannulla rapeaksi.','Lisää currytahna ja kookosmaito.','Lisää paprikat, anna hautua 10 min, tarjoile riisin kera.'],
  r48: ['Keitä pasta al denteksi.','Sekoita pestoon ja parmesaaniin.','Lisää tomaatti ja pinjansiemenet, tarjoile.'],
  r49: ['Kuullota sipuli ja valkosipuli, lisää härkis.','Lisää tomaattimurska ja oregano. Hauduta 15 min.','Tarjoile keitetyn pastan ja juuston kanssa.'],
  r50: ['Keitä riisi maidossa hiljaa noin 45 min, sekoittele.','Lisää suola ja sokeri.','Tarjoile sekahedelmäkiisselin kanssa.'],
};

// Liitä vaiheet resepteihin
if (window.DEFAULT_RECIPES) {
  window.DEFAULT_RECIPES.forEach(r => { r.steps = RECIPE_STEPS[r.id] || []; });
}
window.RECIPE_STEPS = RECIPE_STEPS;
